server :
  port : 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                        - Path=/auth/**
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/

